const { ethers } = require('hardhat');
const { expect } = require('chai')
const path = require('path')
const Util = require('./util.js')
const util = new Util()



describe('Burn tokens', () => {
  beforeEach(async () => {
    await util.deploy();      
  })
  it('should burn directly via vault contract', async()=>{
    await util.cloneHandler(util.deployer.address)
    let emblemAddress = await util.factory.emblemImplementation()
    let emblemContract = util.getEmblemVault(emblemAddress, util.deployer)    
    await util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    let owner = await emblemContract.ownerOf(1)
    await expect(owner).to.equal(util.deployer.address)
    await emblemContract.burn(1)
    owner = emblemContract.ownerOf(1)
    expect(owner).to.be.revertedWith("003002")    
  })
  it('should not claim via handler without permission', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    let emblemAddress = await util.factory.emblemImplementation()
    let emblemContract = util.getEmblemVault(emblemAddress, util.deployer)    
    await util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    let owner = await emblemContract.ownerOf(1)
    await expect(owner).to.equal(util.deployer.address)
    let tx = util.claimer.claim(emblemAddress, 1)
    expect(tx).to.be.revertedWith("003004")
  })
  it.only('should claim erc721 via handler with permission', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    await util.handler.registerContract(util.claimer.address, 6)    
    await claimedContract.registerContract(util.handler.address, 3)
    let emblemAddress = await util.factory.emblemImplementation()
    let emblemContract = util.getEmblemVault(emblemAddress, util.deployer)
    await util.handler.registerContract(emblemAddress, 2)
    await util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    let owner = await emblemContract.ownerOf(1)
    expect(owner).to.equal(util.deployer.address)
    let approved = await emblemContract.isApprovedForAll(util.deployer.address, util.handler.address)
    expect(approved).to.be.false
    await emblemContract.setApprovalForAll(util.handler.address, true)
    approved = await emblemContract.isApprovedForAll(util.deployer.address, util.handler.address)
    expect(approved).to.be.true
    let isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.false
    await util.handler.claim(emblemAddress,1, 0)
    isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.true
    let claimedBy = await util.claimer.claimedBy(emblemAddress, 1)
    expect(claimedBy[0]).to.equal(util.deployer.address)
    expect(claimedBy[1]).to.equal('record')
  })
  it.only('should claim erc1155 via handler with permission', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    await util.handler.registerContract(util.claimer.address, 6)
    await claimedContract.registerContract(util.handler.address, 3)
    ERC1155 = util.getERC1155((await util.factory.erc1155Implementation()), util.deployer)
    await util.handler.registerContract(ERC1155.address, 1)
    await ERC1155.mint(util.deployer.address, 789, 1)
    let serialNumber = await ERC1155.getSerial(789, 0)
    console.log('serialNumber', serialNumber)
    await ERC1155.setApprovalForAll(util.handler.address, true)
    let isClaimed = await util.claimer.isClaimed(ERC1155.address, serialNumber, [])
    expect(isClaimed).to.be.false
    await util.handler.claim(ERC1155.address, 789, serialNumber)
    isClaimed = await util.claimer.isClaimed(ERC1155.address, serialNumber, [])
    expect(isClaimed).to.be.true
    let claimedBy = await util.claimer.claimedBy(ERC1155.address, serialNumber)
    expect(claimedBy[0]).to.equal(util.deployer.address)
    expect(claimedBy[1]).to.equal('record')
    let serialTokenId = await ERC1155.getSerialForTokenId(serialNumber)
    expect(serialTokenId).to.equal(789)
    let lastOwner = await ERC1155.getOwnerOfSerial(serialNumber)
    expect(lastOwner).to.equal(util.deployer.address)
  })
  it.only('should not be able to mint previously claimed erc721 vault', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    await util.handler.registerContract(util.claimer.address, 6)
    await claimedContract.registerContract(util.handler.address, 3)
    let emblemAddress = await util.factory.emblemImplementation()
    let emblemContract = util.getEmblemVault(emblemAddress, util.deployer)
    await util.handler.registerContract(emblemAddress, 2)
    await util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    await emblemContract.setApprovalForAll(util.handler.address, true)
    let isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.false
    await util.handler.claim(emblemAddress, 1, 0)
    isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.true
    let tx = util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    expect(tx).to.be.revertedWith("003006")
    let claimedBy = await util.claimer.claimedBy(emblemAddress, 1)
    expect(claimedBy[0]).to.equal(util.deployer.address)
    expect(claimedBy[1]).to.equal('record')
  })
  it('unminted should not return claimed', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    let emblemAddress = await util.factory.emblemImplementation()
    let isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.false  
    let claimedBy = await util.claimer.claimedBy(emblemAddress, 1)
    expect(claimedBy[0]).to.equal('0x0000000000000000000000000000000000000000')
    expect(claimedBy[1]).to.equal('unknown')  
  })
  it('burnt via emblem vault should not return claimed', async()=>{
    await util.cloneHandler(util.deployer.address)
    await util.cloneClaimed(util.deployer.address)
    let claimedContract = util.getClaimed(util.claimer.address, util.deployer)
    await claimedContract.initialize()
    let emblemAddress = await util.factory.emblemImplementation()
    let emblemContract = util.getEmblemVault(emblemAddress, util.deployer)
    await util.handler.mint(emblemAddress, util.deployer.address, 1, "test", 0x0)
    await emblemContract.burn(1)
    let isClaimed = await util.claimer.isClaimed(emblemAddress, 1, [])
    expect(isClaimed).to.be.false
    let claimedBy = await util.claimer.claimedBy(emblemAddress, 1)
    expect(claimedBy[0]).to.equal('0x0000000000000000000000000000000000000000')
    expect(claimedBy[1]).to.equal('unknown')
  })
})
