const { ethers } = require('hardhat');
const { CID } = require('multiformats/cid');
const { expect } = require('chai')
const path = require('path')
const Util = require('./util.js')
const HDWalletProvider = require("@truffle/hdwallet-provider")
const Web3 = require('web3');
const TEST_CALLBACK_FUNCTION = "0x684ee7de" //web3.eth.abi.encodeFunctionSignature('testCallback(address _from, address _to, uint256 tokenId)').substr(0, 10)
const TEST_REVERT_CALLBACK_FUNCTION = "0x5d1c03dd"
const TEST_FAKE_CALLBACK_FUNCTION = "0x4e1c03dd"

const CALLBACK_TYPE = {"MINT": 0,"TRANSFER": 1,"CLAIM":2}
const REGISTRATION_TYPE = {"EMPTY": 0, "ERC1155": 1, "ERC721":2, "HANDLER":3, "ERC20":4, "BALANCE":5, "CLAIM":6, "UNKNOWN":7, "FACTORY":8, "STAKING": 9, "BYPASS": 10}// 0 EMPTY, 1 ERC1155, 2 ERC721, 3 HANDLER, 4 ERC20, 5 BALANCE, 6 CLAIM 7 UNKNOWN

const util = new Util()
let ERC1155, ERC1155V1

describe('ERC1155', () => {
    beforeEach(async ()=>{
        await util.deployHandler()
        await util.deployBalanceUpgradable()
        await util.deployClaimedUpgradable()
        await util.deployERC721Factory()
        await util.deployERC20Factory()
        await util.deployERC1155Factory()
        ERC1155 = util.erc1155Factory.clone
        await util.erc1155Factory.createClone(util.deployer.address)
        let clones = await util.erc1155Factory.getClones()
        ERC1155V1 = util.getERC1155(clones[1], util.deployer)
      })
    describe('V2 Upgradable', ()=>{
        it('should deploy ERC1155 Vaults', async ()=>{
            expect(ERC1155.address).to.exist
        })
        it('should return proper uri', async ()=>{
            let uri = await ERC1155.uri(1337)
            expect(uri).to.equal("https://api.emblemvault.io/s:evmetadata/meta/1337")
        })
        it('should deploy stream', async ()=>{
            let streamAddress = await ERC1155.streamAddress()
            let stream = util.getContract(streamAddress, "Stream", util.deployer)
            expect(await ERC1155.owner()).to.equal(util.deployer.address)
            expect(await stream.owner()).to.equal(util.deployer.address)
        })
        describe('Events',()=>{
            it('only admin can emit events', async ()=>{
                ERC1155 = util.getERC1155(ERC1155.address, util.bob)
                let tx =  ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1])
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")
            })
            it('should emit one transfer event', async ()=>{
              expect(ERC1155.address).to.exist
              let tx =  await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1])
              let result = await tx.wait()
              expect(result.events.length).to.equal(1)
              expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
              expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
              expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
              expect(result.events[0].args.id).to.equal(1234)
              expect(result.events[0].args.value).to.equal(1)
            })

            it('should emit two transfer events when multiple amounts', async ()=>{
                expect(ERC1155.address).to.exist
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1, 10])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[1].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(10)
            })
            it('should emit two transfer events when multiple to addresses and multiple amounts', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5", "0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1, 10])
                let result = await tx.wait()
                console.log(result.events)
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[1].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(10)
              })
              it('should emit two transfer events when multiple to addresses and single amount', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5", "0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1])
                let result = await tx.wait()
                console.log(result.events)
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
        
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[1].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(1)
              })
        
              it('should emit multiple transfer events when multiple from addresses', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000001"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000001")
                expect(result.events[1].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(1)
              })
        
              it('should emit multiple transfer events when multiple from addresses and multiple amounts', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000001"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1, 10])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000001")
                expect(result.events[1].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(10)
              })
        
              it('should emit multiple transfer events when multiple from addresses, multiple to addresses and multiple amounts', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5"],[1234],["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000001"], ["0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5", "0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1, 10])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                expect(result.events[1].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000001")
                expect(result.events[1].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(10)
              })
        
              it('should emit multiple transfer events when multiple operators', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5", "0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1234],["0x0000000000000000000000000000000000000000"], ["0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                expect(result.events[1].args.operator).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[1].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(1)
              })
              it('should emit multiple transfer events when multiple operators and multiple to', async ()=>{
                let tx = await ERC1155['makeEvents(address[],uint256[],address[],address[],uint256[])'](["0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5", "0x2d922712f5e99428c65b44f09Ea389373d185bB3"],[1234, 1234],["0x0000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000"], ["0x2d922712f5e99428c65b44f09Ea389373d185bB3", "0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5"],[1, 10])
                let result = await tx.wait()
                expect(result.events.length).to.equal(2)
                expect(result.events[0].args.operator).to.equal("0x3B31925EeC78dA3CF15c4503604c13b0eEBC57e5")
                expect(result.events[0].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[0].args.to).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[0].args.id).to.equal(1234)
                expect(result.events[0].args.value).to.equal(1)
                expect(result.events[1].args.operator).to.equal("0x2d922712f5e99428c65b44f09Ea389373d185bB3")
                expect(result.events[1].args.from).to.equal("0x0000000000000000000000000000000000000000")
                expect(result.events[1].args.to).to.equal("0x1684469EA0Ef1dB1dB91DA9524ba6022FDbd06E5")
                expect(result.events[1].args.id).to.equal(1234)
                expect(result.events[1].args.value).to.equal(10)
              })
        })
        describe('Upgrade', ()=>{
            it('Should not be an upgrade by default', async ()=>{
              let upgraded = await ERC1155.isUpgrade()
              expect(upgraded).to.be.false
            })
            it('Should have 2 unique contracts', async()=>{
                expect(ERC1155V1.address).to.not.equals(ERC1155.address)
            })
            it('non admin can not set upgrade', async ()=>{
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.upgradeFrom(ERC1155.address)
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")
                let upgraded = await ERC1155.isUpgrade()
                expect(upgraded).to.be.false
            })
            it('admin can set upgrade', async ()=>{
                await ERC1155.upgradeFrom(ERC1155V1.address)
                console.log("tired")
                let upgraded = await ERC1155.isUpgrade()
                let upgradeAddress = await ERC1155.upgradedFrom()
                expect(upgraded).to.be.true
                expect(upgradeAddress).to.equal(ERC1155V1.address)
            })
        
            it('admin can not set upgrade twice', async ()=>{
                await ERC1155.upgradeFrom(ERC1155V1.address)
                let tx = ERC1155.upgradeFrom(ERC1155V1.address)
                await expect(tx).to.be.revertedWith("Contract already an upgrade")
            })
        
            it('upgraded checks balance of old contract if not seen', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                let oldBalance = await ERC1155V1.balanceOf(util.bob.address, 1337)
                let newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(oldBalance).to.equal(1)
                expect(newBalance).to.equal(0)
                await ERC1155.upgradeFrom(ERC1155V1.address)
                newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(newBalance).to.equal(1)
            })
        
            it('upgraded checks allowance of new contract if not seen', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                ERC1155V1 = util.getERC1155(ERC1155V1.address, util.bob)
                await ERC1155V1.setApprovalForAll(util.deployer.address, true)
                let oldAllowance = await ERC1155V1.isApprovedForAll(util.bob.address, util.deployer.address)
                let newAllowance = await ERC1155.isApprovedForAll(util.bob.address, util.deployer.address)
                expect(oldAllowance).to.be.true
                expect(newAllowance).to.be.false
                await ERC1155.upgradeFrom(ERC1155V1.address)
                newBalance = await ERC1155.isApprovedForAll(util.bob.address, util.deployer.address)
                expect(newBalance).to.equal(false)
            })
        
            it('minting marks address seen', async ()=>{
                await ERC1155.toggleSerialization()
                let seen = await ERC1155.seen(util.bob.address)
                expect(seen).to.be.false
                await ERC1155.mint(util.bob.address, 1337, 1)
                seen = await ERC1155.seen(util.bob.address)
                expect(seen).to.be.true
            })
        
            it('minting combines old and new balances', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155.toggleSerialization()
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                let oldBalance = await ERC1155V1.balanceOf(util.bob.address, 1337)
                let newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(oldBalance).to.equal(1)
                expect(newBalance).to.equal(0)
                await ERC1155.upgradeFrom(ERC1155V1.address)
                await ERC1155.mint(util.bob.address, 1337, 1)
                newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(newBalance).to.equal(2)
            })
            
            it('minting to old after minting on new does not effect new contract balance', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155.toggleSerialization()
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                await ERC1155.upgradeFrom(ERC1155V1.address)
                await ERC1155.mint(util.bob.address, 1337, 1)
                newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(newBalance).to.equal(2)
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                newBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                expect(newBalance).to.equal(2)
                oldBalance = await ERC1155V1.balanceOf(util.bob.address, 1337)
                expect(oldBalance).to.equal(2)
            })
            it('transfering 2 unseen addresses makes both seen', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155.toggleSerialization()
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                await ERC1155V1.mint(util.alice.address, 1337, 1)
                await ERC1155.upgradeFrom(ERC1155V1.address)
                let seenBob = await ERC1155.seen(util.bob.address)
                let seenAlice = await ERC1155.seen(util.alice.address)
                expect(seenBob).to.be.false
                expect(seenAlice).to.be.false
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                await ERC1155.safeTransferFrom(util.bob.address, util.alice.address, 1337, 1, 0x0)
                seenBob = await ERC1155.seen(util.bob.address)
                seenAlice = await ERC1155.seen(util.alice.address)
                expect(seenBob).to.be.true
                expect(seenAlice).to.be.true
                let bobBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                let aliceBalance = await ERC1155.balanceOf(util.alice.address, 1337)
                expect(bobBalance).to.equal(0)
                expect(aliceBalance).to.equal(2)
            })
        
            it('transfering from 1 unseen address makes it seen', async ()=>{
                await ERC1155V1.toggleSerialization()
                await ERC1155.toggleSerialization()
                await ERC1155V1.mint(util.deployer.address, 1337, 10)
                await ERC1155V1.mint(util.bob.address, 1337, 1)
                await ERC1155.upgradeFrom(ERC1155V1.address)
                await ERC1155.mint(util.alice.address, 1337, 1)
                let aliceBalance = await ERC1155.balanceOf(util.alice.address, 1337)
                expect(aliceBalance).to.equal(1)
                let seenBob = await ERC1155.seen(util.bob.address)
                let seenAlice = await ERC1155.seen(util.alice.address)
                expect(seenBob).to.be.false
                expect(seenAlice).to.be.true
                ERC1155 = await util.getERC1155(ERC1155.address, util.alice)
                await ERC1155.safeTransferFrom(util.alice.address, util.bob.address, 1337, 1, 0x0)
                seenBob = await ERC1155.seen(util.bob.address)
                seenAlice = await ERC1155.seen(util.alice.address)
                expect(seenBob).to.be.true
                expect(seenAlice).to.be.true
                let bobBalance = await ERC1155.balanceOf(util.bob.address, 1337)
                aliceBalance = await ERC1155.balanceOf(util.alice.address, 1337)
                expect(bobBalance).to.equal(2)
                expect(aliceBalance).to.equal(0)
            })
        })
        describe('Burn', ()=>{
            it('should burn', async()=>{
                await ERC1155.toggleSerialization()
                await ERC1155.mint(util.deployer.address, 789, 1)
                let balanceERC1155 = await ERC1155.balanceOf(util.deployer.address, 789)
                expect(balanceERC1155).to.equal(1)
                await ERC1155.burn(util.deployer.address, 789, 1)
                balanceERC1155 = await ERC1155.balanceOf(util.deployer.address, 789)
                expect(balanceERC1155).to.equal(0)
            })
        })
        describe('Mint', ()=>{
            it('should mint', async()=>{
                await ERC1155.toggleSerialization()
                let balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 789)
                expect(balanceERC1155).to.equal(0)
                await ERC1155.mint(util.bob.address, 789, 2)
                balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 789)
                expect(balanceERC1155).to.equal(2)
            })
        
            it('should not mint directly if owned by handler', async()=>{
                await ERC1155.toggleSerialization()
                let balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 789)
                expect(balanceERC1155).to.equal(0)
                await ERC1155.transferOwnership(util.handler.address)
                let tx = ERC1155.mint(util.bob.address, 789, 2)
                expect(tx).to.be.revertedWith('018001')
            })
        
            // it('should mint via handler with signature if signer is a witness', async () => {
            //     await ERC1155.transferOwnership(util.handler.address)
            //     await util.handler.changePrice(0)
            //     await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
            //     var provider = util.selectProvider("mainnet")
            //     var web3 = new Web3(provider)
            //     let hash = web3.utils.soliditySha3(ERC1155.address, util.deployer.address, 123, 111, "payload")
            //     let sig = await sign(web3, hash)
            //     let balance = await ERC1155.balanceOf(util.deployer.address, 123)
            //     expect(balance.toNumber()).to.equal(0)
            //     await util.handler.buyWithSignature(ERC1155.address, util.deployer.address, 123, "payload", 111, sig)
            //     balance = await ERC1155.balanceOf(util.deployer.address, 123)
            //     expect(balance.toNumber()).to.equal(1)
            //   })
        
            it('should mint via handler with signed price', async () => {
                let serialized = await ERC1155.isSerialized()
                console.log("serialized", serialized)
                await ERC1155.toggleSerialization()
                await ERC1155.transferOwnership(util.handler.address)
                let covalAddress = util.ERC1155.address
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC1155.address, covalAddress, 0, util.deployer.address, 123, 111, "payload")
                let sig = await sign(web3, hash)
                let balance = await ERC1155.balanceOf(util.deployer.address, 123)
                expect(balance.toNumber()).to.equal(0)
                await util.handler.buyWithSignedPrice(ERC1155.address, covalAddress, 0, util.deployer.address, 123, "payload", 111, sig, util.serializeUintToBytes(0))
                balance = await ERC1155.balanceOf(util.deployer.address, 123)
                expect(balance.toNumber()).to.equal(1)
              })
    
              it('MINT sig: for testing purposes only', async () => {
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3("0x125355e3A87CB49ABD798bD96E7C5dA6F509cD09", "0x0b815bd8a298c2788c5b36e33d75a65cb29a5ab4", 100000000, "0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111", 123, 5555, "payload")
                console.log("hash", hash)
                let sig = await sign(web3, hash)
                console.log("sig", sig)
                console.log("serial", util.serializeUintToBytes(0))
              })
        })
    
        describe('Bypass', ()=>{
            beforeEach(async()=>{
                await ERC1155.toggleSerialization()
            })
            it('not allow bypass if bypass not allowed', async()=>{
                await ERC1155.mint(util.deployer.address, 789, 1)
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0x0)
                await expect(tx).to.be.revertedWith("ERC1155: caller is not owner nor approved nor bypasser")
            })
            it('not allow bypass if bypass allowed and not registered as bypasser', async()=>{
                await ERC1155.mint(util.deployer.address, 789, 1)
                await ERC1155.toggleBypassability()
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0x0)
                await expect(tx).to.be.revertedWith("ERC1155: caller is not owner nor approved nor bypasser")
            })
            it('only admin can add bypasser', async()=>{
                await ERC1155.mint(util.deployer.address, 789, 1)
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.registerContract(util.bob.address, REGISTRATION_TYPE.BYPASS)
                await expect(tx).to.be.revertedWith("Contract is not registered nor Owner")
            })
            it('not allow bypass if bypass allowed and registered as bypasser but wrong id', async()=>{
                await ERC1155.mint(util.deployer.address, 321, 1)
                let balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 321)
                expect(balanceERC1155).to.equal(0)
                await ERC1155.toggleBypassability()
                await ERC1155.addBypassRule(util.bob.address, "0xf242432a", 789);
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 321, 1, 0x0)
                await expect(tx).to.be.revertedWith("ERC1155: caller is not owner nor approved nor bypasser")
            })
            it('allow bypass if bypass for tokenid allowed and registered as bypasser', async()=>{
                await ERC1155.mint(util.deployer.address, 789, 1)
                let balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 789)
                expect(balanceERC1155).to.equal(0)
                await ERC1155.toggleBypassability()
                await ERC1155.addBypassRule(util.bob.address, "0xf242432a", 789);
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                await ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0x0)
                balanceERC1155 = await ERC1155.balanceOf(util.bob.address, 789)
                expect(balanceERC1155).to.equal(1)
            })
            it('not allow bypass of ownerOnly if no valid rule', async()=>{
                let currentUri = await ERC1155.uri(789);
                expect(currentUri).to.equal("https://api.emblemvault.io/s:evmetadata/meta/789")
                await ERC1155.toggleBypassability()
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                let tx = ERC1155.setURI("foo.bar")
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")
                
            })
            it('allow bypass of ownerOnly if valid rule', async()=>{
                let currentUri = await ERC1155.uri(789);
                expect(currentUri).to.equal("https://api.emblemvault.io/s:evmetadata/meta/789")
                await ERC1155.toggleBypassability()
                await ERC1155.addBypassRule(util.bob.address, "0x02fe5305", 0)
                ERC1155 = await util.getERC1155(ERC1155.address, util.bob)
                await ERC1155.setURI("foo.bar/")
                currentUri = await ERC1155.uri(789);
                expect(currentUri).to.equal("foo.bar/789")
            })
        })
        
        
        describe('Non-Fungibility', ()=>{
            it('should be serialized by default', async ()=>{
                let serialized = await ERC1155.isSerialized()
                expect(serialized).to.equal(true)
            })
            it('non owner can not toggle serializability', async ()=>{
                ERC1155 = util.getERC1155(util.erc1155.address, util.bob)            
                let tx = ERC1155.toggleSerialization()
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")
            })
            it('owner can toggle serializability', async ()=>{            
                await ERC1155.toggleSerialization()
                let serialized = await ERC1155.isSerialized()
                expect(serialized).to.equal(false)
            })
            it('should not mint serialnumber if serialization is disabled', async ()=>{
                await ERC1155.toggleSerialization()
                await ERC1155.mint(util.deployer.address, 789, 1)
                let serialnumber =  await ERC1155.getSerial(789, 0)
                expect(serialnumber).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('should not allow turning off serization if any serialized items exist', async()=>{
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(789))
                let tx = ERC1155.toggleSerialization()
                await expect(tx).to.be.revertedWith('Already has serialized items')
            })
        })
        describe('Claim', ()=>{
            it('should claim erc1155 via handler with permission', async()=>{
                // await util.cloneClaimed(util.deployer.address)
                let claimedContract = util.claimedUpgradable
                await util.handler.registerContract(util.claimedUpgradable.address, 6)
                await claimedContract.registerContract(util.handler.address, 3)
                await util.handler.registerContract(ERC1155.address, 1)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(789))
                let serialNumber = await ERC1155.getSerial(789, 0)
                let serialTokenId = await ERC1155.getTokenIdForSerialNumber(serialNumber)
                expect(serialTokenId).to.equal(789)
                await ERC1155.setApprovalForAll(util.handler.address, true)
                let isClaimed = await util.claimedUpgradable.isClaimed(ERC1155.address, serialNumber, [])
                expect(isClaimed).to.be.false
                let hasClaimed = await util.claimedUpgradable.getClaimsFor(util.deployer.address)
                expect(hasClaimed.length).to.equal(0)
                await util.handler.claim(ERC1155.address, 789)
                isClaimed = await util.claimedUpgradable.isClaimed(ERC1155.address, serialNumber, [])
                expect(isClaimed).to.be.true
                let claimedBy = await util.claimedUpgradable.claimedBy(ERC1155.address, serialNumber)
                expect(claimedBy[0]).to.equal(util.deployer.address)
                expect(claimedBy[1]).to.equal('record')
                serialTokenId = await ERC1155.getTokenIdForSerialNumber(serialNumber)
                expect(serialTokenId).to.equal(789)
                let newOwner = await ERC1155.getOwnerOfSerial(serialNumber)
                expect(newOwner).to.equal("0x0000000000000000000000000000000000000000")
                hasClaimed = await util.claimedUpgradable.getClaimsFor(util.deployer.address)
                console.log('hasClaimed', hasClaimed)
                expect(serialNumber).to.equal(hasClaimed[0])
              })
            it('should get correct serialNumber for owner and tokenId after claims', async()=>{
                let claimedContract = util.claimedUpgradable
                await util.handler.registerContract(util.claimedUpgradable.address, 6)
                await claimedContract.registerContract(util.handler.address, 3)
                await util.handler.registerContract(ERC1155.address, 1)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 2, util.serializeUintArrayToBytes([2,3]))
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(4))
                await ERC1155.setApprovalForAll(util.handler.address, true)
                let firstSerialByOwner = await ERC1155.getFirstSerialByOwner(util.deployer.address, 789)
                expect(firstSerialByOwner).to.equal(2)
                await ERC1155.transferOwnership(util.handler.address)
                await util.handler.claim(ERC1155.address, 789)
                firstSerialByOwner = await ERC1155.getFirstSerialByOwner(util.deployer.address, 789)
                expect(firstSerialByOwner).to.equal(4)
                await util.handler.claim(ERC1155.address, 789)
                firstSerialByOwner = await ERC1155.getFirstSerialByOwner(util.deployer.address, 789)
                expect(firstSerialByOwner).to.equal(3)
                await util.handler.claim(ERC1155.address, 789)
                firstSerialByOwner = await ERC1155.getFirstSerialByOwner(util.deployer.address, 789)
                expect(firstSerialByOwner).to.equal(0)
            })
        })
        describe('Handler Callbacks', ()=>{        
            it('should not allow callback registration in handler without witness')
            it('isRegistered should return false when no handler registered', async()=>{
                await ERC1155.unregisterContract(util.handler.address, 0)
                let registered = await ERC1155.isRegistered(util.handler.address, 3)
                expect(registered).to.equal(false)
            })
            it('isRegistered should return true when a handler is registered', async()=>{
                // await ERC1155.registerContract(util.handler.address, REGISTRATION_TYPE.HANDLER)
                let registered = await ERC1155.isRegistered(util.handler.address, REGISTRATION_TYPE.HANDLER)
                expect(registered).to.equal(true)
            })
            it('isRegistered should return false when a handler is unregistered', async()=>{
                // await ERC1155.registerContract(util.handler.address, REGISTRATION_TYPE.HANDLER)
                let registered = await ERC1155.isRegistered(util.handler.address, REGISTRATION_TYPE.HANDLER)
                expect(registered).to.equal(true)
                await ERC1155.unregisterContract(util.handler.address,0)
                registered = await ERC1155.isRegistered(util.handler.address, REGISTRATION_TYPE.HANDLER)
                expect(registered).to.equal(false)
            })
            it('should allow adding callback if handler registered', async ()=>{            
                // await util.handler.registerContract(ERC1155.address, REGISTRATION_TYPE.ERC1155)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.emblem.address, CALLBACK_TYPE.MINT, 0)
                expect(hasCallback).to.equal(false)
                await util.handler.registerCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                hasCallback = await util.handler.hasCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
            })
            it('should allow grabbing all registered contracts of type', async ()=>{
                // await util.handler.registerContract(ERC1155.address, REGISTRATION_TYPE.ERC1155)
                let registered = await util.handler.getAllRegisteredContractsOfType(REGISTRATION_TYPE.ERC1155)
                expect(registered.length).to.equal(1)
                expect(registered[0]).to.equal(ERC1155.address)
            })
            it('should not have callback of different trigger', async ()=>{            
                // await util.handler.registerContract(ERC1155.address, REGISTRATION_TYPE.ERC1155)            
                await util.handler.registerCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.CLAIM)
                expect(hasCallback).to.equal(false)
            })
            it('should allow multiple callbacks to be registered', async()=>{
                // await util.handler.registerContract(ERC1155.address, REGISTRATION_TYPE.ERC1155)
                await util.handler.registerCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await util.handler.registerCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
                hasCallback = await util.handler.hasCallback(ERC1155.address, util.emblem.address, 1, CALLBACK_TYPE.TRANSFER)
                expect(hasCallback).to.equal(true)
            })
            it('can execute single mint callback', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                ticks = await util.handler.ticks();
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(1)
                expect(lastTokenId).to.equal(1)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can execute multple mint callbacks', async()=>{
                await ERC1155.toggleSerialization()
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await util.handler.mint(ERC1155.address, util.deployer.address, 789, "", "", 2)
                ticks = await util.handler.ticks();
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(2)
                expect(lastTokenId).to.equal(789)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can handle transfer when no callbacks registered', async()=>{
                await ERC1155.toggleSerialization()
                await ERC1155.mint(util.deployer.address, 789, 2)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
                expect(lastFrom).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('can handle transfer when no handler registered', async()=>{
                await ERC1155.toggleSerialization()
                await ERC1155.mint(util.deployer.address, 789, 2)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
                expect(lastFrom).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('can execute single transfer callback', async()=>{
                await ERC1155.toggleSerialization()
                await ERC1155.mint(util.deployer.address, 789, 2)
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 1, 0)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(1)
                expect(lastTokenId).to.equal(789)
                expect(lastTo).to.equal(util.bob.address)
                expect(lastFrom).to.equal(util.deployer.address)
            })
            it('can execute single claim callback', async()=>{
                // await ERC1155.toggleSerialization()
                let claimedContract = util.claimedUpgradable
                await util.handler.registerContract(util.claimedUpgradable.address, 6)
                await claimedContract.registerContract(util.handler.address, 3)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(123))
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.CLAIM, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                await ERC1155.setApprovalForAll(util.handler.address, true)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await util.handler.claim(ERC1155.address, 789)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(1)
                expect(lastTokenId).to.equal(789)
                expect(lastTo).to.equal("0x0000000000000000000000000000000000000000")
                expect(lastFrom).to.equal(util.deployer.address)
            })
            it('can execute multiple mint callbacks', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)            
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                ticks = await util.handler.ticks();
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(2)
                expect(lastTokenId).to.equal(1)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can register wildcard callbacks', async() => {
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)            
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
            })
            it('can register wildcard callback and tokenId callback', async() => {
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)            
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
            })
            it('can execute single wildcard callback', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)            
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.MINT)
                expect(hasCallback).to.equal(true)
                await ERC1155.transferOwnership(util.handler.address)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                ticks = await util.handler.ticks();
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(1)
                expect(lastTokenId).to.equal(1)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can execute wildcard and tokenId callback', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)            
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await util.handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 222)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 222, sig, util.serializeUintToBytes(123))
                ticks = await util.handler.ticks();
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(2)
                expect(lastTokenId).to.equal(1)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can allow minting when no callbacks registered', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await ERC1155.transferOwnership(util.handler.address)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('can revert when registered callback type allows reversion', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_REVERT_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                let tx = util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                await expect(tx).to.be.revertedWith("Callback Reverted")
            })
            it('can revert when registered callback type allows reversion and callback is invalid', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_FAKE_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                let tx = util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                await expect(tx).to.be.revertedWith("Callback Reverted")
            })
            it('can catch revert when registered callback type does not allow reversion', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_REVERT_CALLBACK_FUNCTION, false)
                await ERC1155.transferOwnership(util.handler.address)
                
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                let ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('can catch revert when registered callback type does not allow reversion and is invalid callback', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_FAKE_CALLBACK_FUNCTION, false)
                await ERC1155.transferOwnership(util.handler.address)
                
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                let ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
            })
            it('can continue when one failing callback type does not allow reversion', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_REVERT_CALLBACK_FUNCTION, false)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
                
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                await util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                let ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(1)
                expect(lastTokenId).to.equal(1)
                expect(lastTo).to.equal(util.deployer.address)
            })
            it('can revert when one failing callback type does allow reversion', async()=>{
                let ERC721 = util.emblem
                ERC721.mint(util.deployer.address, 2, "test", 0x0)
                await ERC721.setApprovalForAll(util.handler.address, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_CALLBACK_FUNCTION, false)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 1, CALLBACK_TYPE.MINT, TEST_REVERT_CALLBACK_FUNCTION, true)
                await ERC1155.transferOwnership(util.handler.address)
    
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                let hash = web3.utils.soliditySha3(ERC721.address, ERC1155.address, 2, 1, util.serializeUintToBytes(123), 111)
                let sig = await sign(web3, hash)
                await util.handler.addWitness("0x2b8F310A5fE8D057d7Cf1d70E78Ded35cc291111")
    
                let tx = util.handler.moveVault(ERC721.address, ERC1155.address, 2, 1, 111, sig, util.serializeUintToBytes(123))
                await expect(tx).to.be.revertedWith("Callback Reverted")
                let ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                expect(ticks).to.equal(0)
                expect(lastTokenId).to.equal(0)
                expect(lastTo).to.equal('0x0000000000000000000000000000000000000000')
            })
            
            it('should not allow callback non registrant to remove callback', async()=>{
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let handler = util.getHandler(util.handler.address, util.bob)
                let tx = handler.unregisterCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, 0)
                await expect(tx).to.be.revertedWith("Not owner or Callback registrant")
            })
    
            it('should not allow non contract owner to add tokenId callback', async()=>{
                let handler = util.getHandler(util.handler.address, util.bob)
                let tx = handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")        
            })
            it('should not allow non contract owner to add wildcard callback', async()=>{
                let handler = util.getHandler(util.handler.address, util.bob)
                let tx = handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                await expect(tx).to.be.revertedWith("Not owner or able to bypass")     
            })
            it('should allow contract owner to remove tokenId callback', async()=>{
                let handler = util.getHandler(util.handler.address, util.deployer)
                await handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER)
                expect(hasCallback).to.equal(true)
                await util.handler.unregisterCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, 0)
                hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER)
                expect(hasCallback).to.equal(false)
            })
    
            it('should allow contract owner to remove wildcard callback', async()=>{
                let handler = util.getHandler(util.handler.address, util.deployer)
                await handler.registerWildcardCallback(ERC1155.address, util.handler.address, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.TRANSFER)
                expect(hasCallback).to.equal(true)
                await util.handler.unregisterCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.TRANSFER, 0)
                hasCallback = await util.handler.hasCallback(ERC1155.address, util.handler.address, 0, CALLBACK_TYPE.TRANSFER)
                expect(hasCallback).to.equal(false)
            })
    
            it('should execute multiple callbacks on batch transfer', async()=>{
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(123))
                await ERC1155.mintWithSerial(util.deployer.address, 456, 1, util.serializeUintToBytes(111))
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 456, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await ERC1155.safeBatchTransferFrom(util.deployer.address, util.bob.address, [789, 456], [1,1], 0)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(2)
                expect(lastTokenId).to.equal(456)
                expect(lastTo).to.equal(util.bob.address)
                expect(lastFrom).to.equal(util.deployer.address)
            })
            it('should execute multiple callbacks on transfer of multiple amount', async()=>{
                await ERC1155.mintWithSerial(util.deployer.address, 789, 2, util.serializeUintArrayToBytes([123, 786]))
                await util.handler.registerCallback(ERC1155.address, util.handler.address, 789, CALLBACK_TYPE.TRANSFER, TEST_CALLBACK_FUNCTION, true)
                let ticks = await util.handler.ticks()
                expect(ticks).to.equal(0)
                await ERC1155.safeTransferFrom(util.deployer.address, util.bob.address, 789, 2, 0)
                ticks = await util.handler.ticks()
                let lastTokenId = await util.handler.lastTokenId()
                let lastTo = await util.handler.lastTo()
                let lastFrom = await util.handler.lastFrom()
                expect(ticks).to.equal(2)
                expect(lastTokenId).to.equal(789)
                expect(lastTo).to.equal(util.bob.address)
                expect(lastFrom).to.equal(util.deployer.address)
            })
            it('should execute callbacks on batch mint')
            it('FUNCTION generate: for testing purposes only', async()=>{
                var provider = util.selectProvider("mainnet")
                var web3 = new Web3(provider)
                // let hash = web3.eth.abi.encodeFunctionSignature('catchCallbackFrom(address,address,uint256)').substr(0, 10) //catchCallback(address, address _to, uint256)
                let hash = web3.eth.abi.encodeFunctionSignature('transferFrom(address sender, address recipient, uint256 amount)').substr(0, 10) //getFunctions()
                console.log("hash", hash)
            })
        })
        describe('Serialization', async()=>{
            it('should mint with overloadSerial off', async ()=>{
                await ERC1155.toggleOverloadSerial()
                await ERC1155.mint(util.deployer.address, 789, 1)
                let currentBalance = await ERC1155.balanceOf(util.deployer.address, 789)
                expect(currentBalance).to.equal(1)
            })
            it('can mint with provided serial', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(123))
                let currentBalance = await ERC1155.balanceOf(util.deployer.address, 789)
                expect(currentBalance).to.equal(1)
                let currentSerial = await ERC1155.getFirstSerialByOwner(util.deployer.address, 789)
                expect(currentSerial).to.equal(123)
            })
            it('should not mint with duplicate serial', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(123))
                let tx = ERC1155.mintWithSerial(util.deployer.address, 789, 1, util.serializeUintToBytes(123))
                await expect(tx).to.be.revertedWith("Serial number already used")
            })
            it('should not standard mint when overridable', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                let tx = ERC1155.mint(util.deployer.address, 789, 1)
                await expect(tx).to.be.revertedWith("Must provide serial number")
            })
            it('should not mint amounts over 1 with duplicate encoded serials', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                let tx = ERC1155.mintWithSerial(util.deployer.address, 789, 2, util.serializeUintArrayToBytes([123, 123]))
                await expect(tx).to.be.revertedWith("Serial number already used")
            })
            it('should mint amounts over 1 with encoded serials', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.mintWithSerial(util.deployer.address, 789, 2, util.serializeUintArrayToBytes([123, 456]))
                let serial1 = await ERC1155.getSerial(789, 0)
                let serial2 = await ERC1155.getSerial(789, 1)
                expect(serial1).to.equal(123)
                expect(serial2).to.equal(456)
            })
            it('should not mint batch with duplicate encoded serials', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                let tx = ERC1155.mintBatch(util.deployer.address, [789, 543], [1,1], util.serializeToByteArray([123, 123]))
                await expect(tx).to.be.revertedWith("Serial number already used")
            })
            it('should mint batch with encoded serials', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.mintBatch(util.deployer.address, [789, 543], [1,1], util.serializeToByteArray([123, 456]))
                let serial1 = await ERC1155.getSerial(789, 0)
                let serial2 = await ERC1155.getSerial(543, 0)
                expect(serial1).to.equal(123)
                expect(serial2).to.equal(456)
            })
            it('should mint batch with encoded serials and amounts', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.mintBatch(util.deployer.address, [789, 543], [1,2], util.serializeToByteArray([789, [123, 456]]))
                let serial1 = await ERC1155.getSerial(789, 0)
                let serial2 = await ERC1155.getSerial(543, 0)
                let serial3 = await ERC1155.getSerial(543, 1)
                expect(serial1).to.equal(789)
                expect(serial2).to.equal(123)
                expect(serial3).to.equal(456)
            })
            it('should burn', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.toggleOverloadSerial()
                await ERC1155.mint(util.deployer.address, 789, 1)
                await ERC1155.burn(util.deployer.address, 789, 1)
                let currentBalance = await ERC1155.balanceOf(util.deployer.address, 789)
                expect(currentBalance).to.equal(0)
            })
            it('should claim', async ()=>{
                // await util.deployERC1155Factory(util.handler)
                await ERC1155.toggleOverloadSerial()
                await util.deployClaimedUpgradable()
                await ERC1155.mint(util.deployer.address, 789, 1)
                await ERC1155.setApprovalForAll(util.handler.address, true)
                await util.handler.registerContract(util.claimedUpgradable.address, 6)
                await util.handler.registerContract(ERC1155.address, 1)
                await ERC1155.registerContract(util.handler.address, 3)
                await util.claimedUpgradable.registerContract(util.handler.address, 3)
                await util.handler.claim(ERC1155.address, 789)
                let claims = await util.claimedUpgradable.getClaimsFor(util.deployer.address)
                expect(claims[0]).to.equal("0xb05d86c0f0c086513efc043d0690939fbbe77b6e0e329030bd231360f0d640ea")
            })     
        })
    })
})


async function sign(web3, hash){
    let accounts = await web3.eth.getAccounts()
    let signature = await web3.eth.sign(hash, accounts[0])
    return signature
}